services:
  backend:
    container_name: backend
    build:
      context: ./
    volumes:
      - ./:/cs_uk
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:alpine
    container_name: cs_db
    restart: on-failure
    environment:
      POSTGRES_USER: cs_db
      POSTGRES_PASSWORD: noob_db
      POSTGRES_DB: cs_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  celery-pdf:
    container_name: celery-pdf
    build:
      context: ./
    command: celery --app=core worker -l INFO -Q queue1
    volumes:
      - ./:/cs_uk
    depends_on:
      - redis
    environment:
      - TZ=Asia/Dhaka

  celery-util:
    container_name: celery-util
    build:
      context: ./
    command: celery --app=core worker -l INFO -Q queue2
    volumes:
      - ./:/cs_uk
    depends_on:
      - redis
    environment:
      - TZ=Asia/Dhaka


  celery-beat:
    container_name: celerybeat
    build:
      context: ./
    command: celery --app=core beat -l INFO 
    volumes:
      - ./:/cs_uk
      - celery-beat-schedule:/celerybeat-schedule
    depends_on:
      - redis
      - backend
    environment:
      - TZ=Asia/Dhaka


  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"


volumes:
  db_data:
  celery-beat-schedule:
    driver: local  
