# Generated by Django 5.1.3 on 2024-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_supplierprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
