# Generated by Django 5.1.3 on 2024-11-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_blacklistedtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedtoken',
            name='token_type',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
