# Generated by Django 5.1.3 on 2024-11-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blacklistedtoken_token_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistedtoken',
            name='token_type',
        ),
    ]
