# Generated by Django 5.1.3 on 2024-11-26 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=3)),
                ('delivery_date', models.DateTimeField()),
                ('sended_by_supplier', models.BooleanField(default=False)),
                ('received_by_admin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('delivered', 'Delivered')], default='pending', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.card')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.userprofile')),
                ('supplier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.supplierprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_invoice', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.userprofile')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.order')),
            ],
        ),
    ]
