# Generated by Django 5.1.3 on 2024-11-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=3)),
                ('delivery_date', models.DateTimeField()),
                ('sended_by_supplier', models.BooleanField(default=False)),
                ('received_by_admin', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_invoice', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.userprofile')),
            ],
        ),
    ]
