# Generated by Django 5.1.3 on 2024-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('delivered', 'delivered')], default='pending', max_length=10),
        ),
    ]
