# Generated by Django 5.1.3 on 2024-11-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('order', '0002_order_supplier_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.supplierprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.userprofile'),
        ),
    ]
