# Generated by Django 5.1.3 on 2024-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_code',
            field=models.CharField(max_length=50),
        ),
    ]
