# Generated by Django 5.1.3 on 2024-11-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_supplier_alter_payment_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
