# Generated by Django 5.1.3 on 2024-11-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
